#NatTable state
#Fri Aug 21 22:02:04 EEST 2026
fakturama.views.debitorTable.COLUMN_HEADER.columnWidth.percentageSizing=false
fakturama.views.debitorTable.BODY.columnWidth.defaultSize=100
fakturama.views.productTable.BODY.columnWidth.percentageSizing=false
fakturama.document.voucherItemTable.COLUMN_HEADER.rowHeight.distributeRemainingSpace=true
fakturama.document.voucherItemTable.ROW_HEADER.rowHeight.defaultMinSize=0
fakturama.document.voucherItemTable.BODY.columnWidth.distributeRemainingSpace=true
fakturama.views.productTable.ROW_HEADER.rowHeight.distributeRemainingSpace=false
fakturama.views.productTable.CORNER.rowHeight.resizableByDefault=true
fakturama.views.debitorTable.BODY.rowHeight.defaultSize=20
fakturama.views.productTable.BODY.rowHeight.defaultMinSize=0
fakturama.document.voucherItemTable.BODY.columnWidth.resizableByDefault=true
fakturama.views.productTable.BODY.columnWidth.defaultMinSize=0
fakturama.views.productTable.COLUMN_HEADER.columnWidth.resizableByDefault=true
fakturama.views.debitorTable.CORNER.columnWidth.percentageSizing=false
fakturama.views.productTable.CORNER.rowHeight.defaultSize=20
fakturama.document.voucherItemTable.ROW_HEADER.rowHeight.percentageSizing=false
fakturama.document.voucherItemTable.COLUMN_HEADER.rowHeight.defaultSize=20
fakturama.document.voucherItemTable.COLUMN_HEADER.rowHeight.percentageSizing=false
fakturama.views.debitorTable.ROW_HEADER.rowHeight.distributeRemainingSpace=false
fakturama.document.voucherItemTable.ROW_HEADER.rowHeight.resizableByDefault=true
fakturama.views.productTable.ROW_HEADER.columnWidth.percentageSizing=false
fakturama.document.voucherItemTable.CORNER.columnWidth.resizableByDefault=true
fakturama.views.productTable.BODY.columnWidth.resizableByDefault=true
fakturama.views.productTable.ROW_HEADER.rowHeight.resizableByDefault=true
fakturama.views.debitorTable.ROW_HEADER.columnWidth.percentageSizing=false
fakturama.views.debitorTable.ROW_HEADER.columnWidth.resizableByDefault=true
fakturama.document.voucherItemTable.ROW_HEADER.columnWidth.resizableByDefault=true
fakturama.views.debitorTable.COLUMN_HEADER.rowHeight.percentageSizing=false
fakturama.views.debitorTable.BODY.rowHeight.resizableByDefault=true
fakturama.document.voucherItemTable.COLUMN_HEADER.columnWidth.defaultMinSize=0
fakturama.views.debitorTable.COLUMN_HEADER.columnWidth.defaultMinSize=0
fakturama.document.voucherItemTable.ROW_HEADER.columnWidth.defaultMinSize=0
fakturama.document.voucherItemTable.BODY.columnWidth.defaultMinSize=0
fakturama.views.debitorTable.COLUMN_HEADER.rowHeight.resizableByDefault=true
fakturama.views.productTable.BODY.columnWidth.defaultSize=100
fakturama.views.debitorTable.CORNER.columnWidth.defaultMinSize=0
fakturama.views.productTable.COLUMN_HEADER.columnWidth.defaultSize=100
fakturama.document.voucherItemTable.BODY.rowHeight.defaultSize=20
fakturama.views.debitorTable.BODY.columnWidth.defaultMinSize=0
fakturama.views.productTable.BODY.columnWidth.distributeRemainingSpace=false
fakturama.views.productTable.COLUMN_HEADER.rowHeight.defaultMinSize=0
fakturama.views.productTable.ROW_HEADER.rowHeight.defaultMinSize=0
fakturama.document.voucherItemTable.COLUMN_HEADER.rowHeight.defaultMinSize=0
fakturama.document.voucherItemTable.BODY.columnWidth.defaultSize=100
fakturama.document.voucherItemTable.CORNER.columnWidth.distributeRemainingSpace=true
fakturama.views.debitorTable.CORNER.rowHeight.percentageSizing=false
fakturama.document.voucherItemTable.BODY.rowHeight.percentageSizing=false
fakturama.views.debitorTable.BODY.columnWidth.distributeRemainingSpace=false
fakturama.views.productTable.COLUMN_HEADER.rowHeight.distributeRemainingSpace=false
fakturama.document.voucherItemTable.COLUMN_HEADER.columnWidth.distributeRemainingSpace=true
fakturama.views.debitorTable.COLUMN_HEADER.columnWidth.resizableByDefault=true
fakturama.views.productTable.COLUMN_HEADER.rowHeight.resizableByDefault=true
fakturama.views.productTable.ROW_HEADER.columnWidth.resizableByDefault=true
fakturama.views.debitorTable.CORNER.columnWidth.distributeRemainingSpace=false
fakturama.views.productTable.CORNER.columnWidth.percentageSizing=false
fakturama.views.debitorTable.ROW_HEADER.rowHeight.defaultMinSize=0
fakturama.document.voucherItemTable.CORNER.columnWidth.defaultSize=100
fakturama.document.voucherItemTable.ROW_HEADER.columnWidth.defaultSize=40
fakturama.views.productTable.COLUMN_HEADER.columnWidth.distributeRemainingSpace=false
fakturama.document.voucherItemTable.BODY.rowHeight.defaultMinSize=0
fakturama.document.voucherItemTable.CORNER.columnWidth.percentageSizing=false
fakturama.document.voucherItemTable.CORNER.rowHeight.defaultMinSize=0
fakturama.views.productTable.CORNER.columnWidth.defaultMinSize=0
fakturama.views.debitorTable.CORNER.rowHeight.defaultMinSize=0
fakturama.views.debitorTable.BODY.rowHeight.defaultMinSize=0
fakturama.views.productTable.CORNER.columnWidth.distributeRemainingSpace=false
fakturama.views.debitorTable.COLUMN_HEADER.rowHeight.defaultSize=20
fakturama.views.debitorTable.BODY.columnWidth.resizableByDefault=true
fakturama.views.debitorTable.COLUMN_HEADER.rowHeight.distributeRemainingSpace=false
fakturama.document.voucherItemTable.CORNER.rowHeight.defaultSize=20
fakturama.views.debitorTable.ROW_HEADER.rowHeight.defaultSize=40
fakturama.views.productTable.ROW_HEADER.rowHeight.defaultSize=40
fakturama.views.debitorTable.ROW_HEADER.columnWidth.defaultMinSize=0
fakturama.views.debitorTable.ROW_HEADER.columnWidth.defaultSize=40
fakturama.views.debitorTable.ROW_HEADER.rowHeight.resizableByDefault=true
fakturama.views.debitorTable.CORNER.columnWidth.resizableByDefault=true
fakturama.views.productTable.ROW_HEADER.columnWidth.defaultSize=40
fakturama.views.productTable.BODY.rowHeight.defaultSize=20
fakturama.document.voucherItemTable.BODY.rowHeight.resizableByDefault=true
fakturama.views.debitorTable.COLUMN_HEADER.columnWidth.defaultSize=100
fakturama.document.voucherItemTable.CORNER.rowHeight.percentageSizing=false
fakturama.views.debitorTable.CORNER.rowHeight.resizableByDefault=true
fakturama.document.voucherItemTable.COLUMN_HEADER.rowHeight.resizableByDefault=true
fakturama.views.productTable.COLUMN_HEADER.columnWidth.percentageSizing=false
fakturama.views.debitorTable.ROW_HEADER.rowHeight.percentageSizing=false
fakturama.views.productTable.ROW_HEADER.rowHeight.percentageSizing=false
fakturama.views.debitorTable.CORNER.rowHeight.defaultSize=20
fakturama.document.voucherItemTable.COLUMN_HEADER.columnWidth.percentageSizing=false
fakturama.views.debitorTable.COLUMN_HEADER.columnWidth.distributeRemainingSpace=false
fakturama.views.debitorTable.CORNER.rowHeight.distributeRemainingSpace=false
fakturama.document.voucherItemTable.CORNER.rowHeight.distributeRemainingSpace=true
fakturama.document.voucherItemTable.ROW_HEADER.columnWidth.percentageSizing=false
fakturama.views.productTable.CORNER.columnWidth.defaultSize=100
fakturama.document.voucherItemTable.COLUMN_HEADER.columnWidth.defaultSize=100
fakturama.views.productTable.BODY.rowHeight.resizableByDefault=true
fakturama.document.voucherItemTable.COLUMN_HEADER.columnWidth.resizableByDefault=true
fakturama.document.voucherItemTable.BODY.columnWidth.percentageSizing=true
fakturama.document.voucherItemTable.CORNER.columnWidth.defaultMinSize=0
fakturama.views.productTable.CORNER.rowHeight.defaultMinSize=0
fakturama.views.productTable.ROW_HEADER.columnWidth.defaultMinSize=0
fakturama.document.voucherItemTable.CORNER.rowHeight.resizableByDefault=true
fakturama.views.productTable.CORNER.columnWidth.resizableByDefault=true
fakturama.document.voucherItemTable.ROW_HEADER.rowHeight.distributeRemainingSpace=true
fakturama.views.debitorTable.ROW_HEADER.columnWidth.distributeRemainingSpace=false
fakturama.views.productTable.COLUMN_HEADER.rowHeight.percentageSizing=false
fakturama.document.voucherItemTable.ROW_HEADER.rowHeight.defaultSize=40
fakturama.views.debitorTable.BODY.columnWidth.percentageSizing=false
fakturama.views.productTable.BODY.rowHeight.percentageSizing=false
fakturama.views.productTable.CORNER.rowHeight.distributeRemainingSpace=false
fakturama.views.debitorTable.BODY.rowHeight.percentageSizing=false
fakturama.views.debitorTable.CORNER.columnWidth.defaultSize=100
fakturama.views.productTable.COLUMN_HEADER.columnWidth.defaultMinSize=0
fakturama.views.debitorTable.COLUMN_HEADER.rowHeight.defaultMinSize=0
fakturama.views.productTable.CORNER.rowHeight.percentageSizing=false
fakturama.views.debitorTable.BODY.rowHeight.distributeRemainingSpace=false
fakturama.document.voucherItemTable.BODY.rowHeight.distributeRemainingSpace=true
fakturama.document.voucherItemTable.ROW_HEADER.columnWidth.distributeRemainingSpace=true
fakturama.views.productTable.ROW_HEADER.columnWidth.distributeRemainingSpace=false
fakturama.views.productTable.COLUMN_HEADER.rowHeight.defaultSize=20
fakturama.views.productTable.BODY.rowHeight.distributeRemainingSpace=false
